---
- hosts: all
  tasks:
    - name: HTTP OS Package Installation
      package: name=httpd state=present
    - name: NTP File Configurations
      copy: src=./index.html dest=/var/www/html/index.html
    - name: To start HTTPD services
      service: name=httpd state=started enabled=yes
