---
- hosts: all
  tasks:
    - name: HTTP OS Package Installation
      package: name=httpd state=present
    - name: NTP File Configurations
      file: path=/var/www/http/index.html state=file
    - name: To start HTTPD services
      service: name=httpd state=started enabled=yes
